[build]
  functions = "functions/src"
  functionsSource = "functions/dist"
  publish = "dist"
  command = "npm run build"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "dist"
  autoLaunch = false
  framework = "#custom"

[functions]
  directory = "functions/src"

[[redirects]]
  force = true
  from = '/api/*'
  status = 200
  to = '/.netlify/functions/'

[[redirects]]
  from = "*"
  to = "/index.html"
  status = 200
