[build]
  functions = "functions/src"
  functionsSource = "functions/dist"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "dist"
  autoLaunch = true
  framework = "#custom"

[[redirects]]
  from = "*"
  to = "/index.html"
  status = 200
